### ISSUE TITLE
Add callback possibility for the tour

### ISSUE THREAD

**Issue by susannemoog** [tdeuling/typo3-guide#4]
It would be nice to have a concept of callbacks that are called after the user completes actions - so you'd have a JS callback for created a page or something, so we are able to check what parts the user completed. 

This might even be more of a core issue, like a JS Hook system.

**Comment by tdeuling** [comment]
Maybe we should collect the requirements for such a feature - What use cases are really required for guided tour steps?!

A tour step should know, if a user..
* clicked a button
* filled a field
* selected a selectbox value
* ..more?!

Our target is, to make the tour configuration as easy as possible. Therefore we tried to make a simple language/configuration file.

A step configuration for that could look like:
```
step-identifier-1:
  # The requires node defines: what must be happen so that the tour is able to open the next step.
  # If the user clicks the next-button, the tour will check the conditions. 
  # In case of the user didn't have solved the requirements, we will show an additional text with a hint.
  requires:
    # Required, that the user interact with an input field
    input:
      # Input field, where the interaction is required
      selector: input[data-identifier='example-field']
      # text: * means, any text is required
      text: *
      # text: 'My title' means, the user must enter exactly this string
      text: 'My title'
    # Required, that the user clicked on any DOM element
    click:
      # Selector for DOM element, which have to be clicked
      selector: a[data-identifier='example-field']
    # Required, that the user selects a selectbox option
    select:
      # Selectbox, where the interaction is required
      selector: select[data-identifier='example-field']
      # value: * means, any option is required
      value: *
      # value: '1' means, the user must select the option with value 1
      value: '1'
```
