### ISSUE TITLE
Event for disable next button in a step

### ISSUE THREAD

**Issue by tdeuling** [tdeuling/typo3-guide#7]
We have to implement a disableNextButton event.

Current workaround:
```
  shown:
    addClass:
      selector: '#popover-button-next'
      class: hidden
```

must be replaced with:
```
  shown:
    disableNextButton: true
```
